services:
  sonnette-api:
    build: .
    container_name: iot-sonnette-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Synchronise le dossier 'database' local avec celui du conteneur
      - ./database:/app/database